// app/lib/language-context.tsx
'use client';

import { createContext, useContext, useState, type ReactNode } from 'react';

export type Lang = 'id' | 'en';

const id = {
  nav: {
    toolsLabel: 'Alat',
    imageConverter: 'Konverter Gambar',
    imageConverterDesc: 'Ubah & kompres gambar',
    imageToPdf: 'Gambar ke PDF',
    imageToPdfDesc: 'Gabung gambar jadi satu PDF',
    htmlToPdf: 'HTML ke PDF',
    htmlToPdfDesc: 'Ubah kode HTML jadi PDF',
    docxToHtml: 'DOCX ke HTML',
    docxToHtmlDesc: 'Ubah dokumen Word jadi HTML',
    pdfCompressor: 'Kompres PDF',
    pdfCompressorDesc: 'Perkecil ukuran PDF',
    qrGenerator: 'Pembuat Kode QR',
    qrGeneratorDesc: 'Buat kode QR',
    bgRemover: 'Hapus Latar Belakang',
    bgRemoverDesc: 'Hapus latar belakang gambar',
    pdfMergeSplit: 'Gabung & Pisah PDF',
    pdfMergeSplitDesc: 'Gabung atau pisah halaman PDF',
    scanToPdf: 'Scan ke PDF',
    scanToPdfDesc: 'Scan dokumen jadi PDF',
    soon: 'SEGERA',
  },
  sidebar: {
    storageStatus: 'Diproses 100% secara lokal',
    effectsLabel: 'Animasi Latar',
    effects: {
      off: 'Mati',
      boxes: 'Kotak Melayang',
      particles: 'Partikel',
      network: 'Jaringan',
      bubbles: 'Gelembung',
      comets: 'Komet',
    },
  },
  theme: {
    dark: 'Gelap',
    light: 'Terang',
    system: 'Sistem',
    accents: {
      purple: 'Ungu',
      green: 'Hijau',
      yellow: 'Kuning',
      blue: 'Biru',
      orange: 'Oranye',
      pink: 'Pink',
      teal: 'Teal',
      red: 'Merah',
    },
  },
  toolsPage: {
    title: 'Semua Alat',
    subtitle: 'Pilih alat yang mau dipakai — cepat, ringan, dan langsung bisa dipakai.',
  },
  search: {
    openLabel: 'Cari',
    placeholder: 'Cari alat atau halaman...',
    toolsGroup: 'Alat',
    pagesGroup: 'Halaman',
    noResults: (query: string) => `Gak ada hasil untuk "${query}"`,
    clearLabel: 'Hapus pencarian',
    tapHint: 'Ketuk untuk memilih',
    navHint: 'navigasi',
    selectHint: 'pilih',
    closeHint: 'tutup',
    soon: 'Segera',
    pages: {
      howItWorks: 'Pelajari cara kerja VoiTzu Tools, langkah demi langkah',
      privacy: 'Kebijakan privasi dan data yang kami simpan',
      contact: 'Hubungi tim VoiTzu Tools',
    },
  },
  footer: {
    tagline:
      'Kumpulan tools kecil yang cepat, ringan, dan gratis — dirancang biar kerjaan konversi file kamu selesai dalam hitungan detik.',
    toolsTitle: 'Alat',
    infoTitle: 'Info',
    howItWorks: 'Cara kerja',
    privacy: 'Privasi',
    contact: 'Kontak',
    soon: 'segera',
    madeWith: 'Dibuat dengan Next.js & Supabase',
  },
  page: {
    eyebrow: 'ALAT · KONVERTER GAMBAR',
    title: 'Konverter Gambar',
    desc: 'Convert gambar ke WebP, PNG, atau JPG secara instan dan tanpa ribet. Atur kualitas dan target ukuran file secara terpisah, lalu download hasilnya dalam hitungan detik.',
    dropTitle: 'Drop gambar di sini atau klik buat pilih file',
    dropSub: 'JPG · PNG · WEBP · GIF · BMP — bisa banyak file sekaligus',
    removeItem: 'Hapus gambar ini dari antrean',
    formatOutput: 'Format Output',
    quality: 'Kualitas',
    lossless: 'Lossless',
    qualityHintPng: 'PNG bersifat lossless, jadi gak ada pengaturan kualitas.',
    qualityHint:
      'Kualitas ini dipakai apa adanya, gak diturunin otomatis. Kalau file masih kegedean, yang dikecilin adalah dimensinya, bukan kualitasnya.',
    targetSize: 'Target Ukuran File',
    targetHint: (max: number) =>
      `Maks ${max}KB (1MB). Kalau hasil di kualitas yang lo pilih masih lebih besar dari target, gambarnya diperkecil dimensinya bertahap sampai muat — kualitasnya tetap sama.`,
    convert: 'Convert Semua File',
    converting: 'Memproses...',
    waiting: 'Menunggu convert',
    download: 'Unduh',
    downloadAll: 'Unduh Semua',
    downloadAllSuccess: (n: number) => (n === 1 ? '1 file diunduh' : `${n} file diunduh`),
    downloadSuccessTitle: 'Unduh berhasil',
    downloadSuccess: (name: string) => name,
    clearAll: 'Hapus semua',
    targetNotReached: '· target gak tercapai, ini yang terkecil bisa didapat',
  },
  privacy: {
    eyebrow: 'INFO · PRIVASI',
    title: 'Kebijakan Privasi',
    intro:
      'Singkatnya: file gambar lo diproses langsung di browser, gak pernah diupload dalam bentuk aslinya. Halaman ini jelasin persisnya data apa yang kami sentuh dan kenapa.',
    updated: 'Berlaku sejak pertama kali kamu membuka VoiTzu Tools — gak ada versi tersembunyi lain.',
    backLabel: 'Kembali ke Konverter Gambar',
    sections: [
      {
        heading: 'Apa yang Kami Proses',
        body: 'Convert, resize, dan kompresi gambar semuanya kejadian di browser lo lewat Canvas API — file asli gak pernah dikirim ke server manapun. Server cuma nerima hasil akhirnya, setelah kamu klik tombol convert.',
      },
      {
        heading: 'Data yang Disimpan',
        body: 'Hasil convert (bukan file asli) otomatis di-backup ke Supabase Storage biar kamu bisa download ulang kalau perlu. Nama file diacak, dan kami gak nyimpen metadata seperti lokasi, device, atau identitas kamu bareng file itu.',
      },
      {
        heading: 'Preferensi di Browser',
        body: 'Pilihan tema (gelap/terang), warna aksen, dan bahasa disimpan di localStorage browser kamu sendiri. Data ini gak pernah kekirim ke server kami — murni buat bikin tampilan tetap sesuai preferensi kamu tiap buka lagi.',
      },
      {
        heading: 'Pihak Ketiga',
        body: 'Kami pakai Supabase Storage sebagai tempat backup hasil convert. Gak ada Google Analytics, Meta Pixel, atau tracker iklan lain yang terpasang di VoiTzu Tools.',
      },
      {
        heading: 'Keamanan',
        body: 'Semua trafik ke server dienkripsi lewat HTTPS. Karena kami gak pernah pegang file asli kamu ataupun data pribadi, permukaan risikonya sekecil mungkin.',
      },
      {
        heading: 'Hak Kamu',
        body: 'Kamu bisa minta hasil convert yang tersimpan di server kami dihapus kapan saja — tinggal hubungi kami lewat kontak di bawah, sebutin nama file atau kira-kira waktu upload-nya.',
      },
      {
        heading: 'Kontak',
        body: 'Ada pertanyaan soal privasi? Kirim email ke cs.voitzu@gmail.com — kami usahain balas secepatnya.',
      },
    ],
  },
  contact: {
    eyebrow: 'INFO · KONTAK',
    title: 'Hubungi Kami',
    intro:
      'Ada pertanyaan, laporan bug, atau ide fitur buat VoiTzu Tools? Kirim pesan lewat form di bawah atau langsung email — kami baca semuanya.',
    backLabel: 'Kembali ke Konverter Gambar',
    infoCardsTitle: 'Cara Lain Menghubungi',
    email: 'cs.voitzu@gmail.com',
    emailNote: 'Rata-rata dibalas dalam 1–2 hari kerja',
    responseTitle: 'Waktu Respons',
    responseBody: 'Kami tim kecil, jadi mohon sabar ya — biasanya kebalas dalam 1–2 hari kerja.',
    bugTitle: 'Nemu Bug?',
    bugBody: 'Sebutin browser, format gambar, dan langkah buat reproduce masalahnya biar cepat kami tangani.',
    form: {
      nameLabel: 'Nama',
      namePlaceholder: 'Nama kamu',
      emailLabel: 'Email',
      emailPlaceholder: 'kamu@email.com',
      subjectLabel: 'Topik',
      subjectPlaceholder: 'Pilih topik pesan',
      subjectOptions: ['Pertanyaan umum', 'Laporan bug', 'Ide fitur', 'Lainnya'],
      messageLabel: 'Pesan',
      messagePlaceholder: 'Tulis pesan kamu di sini...',
      submit: 'Kirim via Email',
      note: 'Tombol ini bakal buka aplikasi email default kamu dengan pesan yang udah keisi otomatis — kami belum punya form yang langsung nyimpen ke server.',
    },
  },
  howItWorks: {
    eyebrow: 'INFO · CARA KERJA',
    title: 'Cara Kerja VoiTzu Tools',
    intro:
      'Semua konversi gambar kejadian langsung di browser kamu, bukan di server kami. Ini alurnya dari awal upload sampai file siap didownload.',
    backLabel: 'Kembali ke Konverter Gambar',
    steps: [
      {
        heading: 'Drop atau Pilih Gambar',
        body: 'Seret file ke area drop atau klik buat pilih dari perangkat kamu. Bisa banyak file sekaligus — format JPG, PNG, WebP, GIF, atau BMP semua didukung sebagai input.',
      },
      {
        heading: 'Atur Format, Kualitas & Ukuran',
        body: 'Pilih format output (WebP/JPG/PNG), geser slider kualitas, dan set target ukuran file kalau perlu. Dua pengaturan ini independen — kualitas gak otomatis diturunin buat ngejar target ukuran.',
      },
      {
        heading: 'Diproses di Browser Kamu',
        body: 'Begitu klik convert, VoiTzu Tools pakai Canvas API bawaan browser buat encode ulang gambarnya. File asli gak pernah ninggalin perangkat kamu di tahap ini.',
      },
      {
        heading: 'Hasil Di-backup Otomatis',
        body: 'Setelah selesai diproses, hanya hasil akhirnya (bukan file asli) yang dikirim dan disimpan ke Supabase Storage, biar kamu bisa akses lagi kalau reload halaman atau ganti perangkat.',
      },
      {
        heading: 'Download Kapan Aja',
        body: 'Klik tombol download buat nyimpen hasilnya ke perangkat kamu. Selesai — gak ada watermark, gak ada limit tersembunyi.',
      },
    ],
    note: 'Penasaran soal data apa aja yang kami simpan? Baca lengkapnya di halaman Privasi.',
    noteLink: 'Lihat Kebijakan Privasi',
  },
  pdfToolPage: {
    eyebrow: 'ALAT · GAMBAR KE PDF',
    title: 'Gambar ke PDF',
    desc: 'Gabungin satu atau banyak gambar jadi satu file PDF dengan cepat. Atur margin dan orientasi halaman, atau biarin ngikutin ukuran gambar aslinya.',
    dropTitle: 'Drop gambar di sini atau klik buat pilih file',
    dropSub: 'JPG · PNG · WEBP · GIF · BMP — bisa pilih banyak sekaligus, urutan pilih jadi urutan halaman',
    imagesSelected: (n: number) => (n === 1 ? '1 gambar dipilih' : `${n} gambar dipilih`),
    removeImage: 'Hapus gambar ini',
    paperSizeLabel: 'Ukuran Kertas',
    paperSizeNames: {
      a3: 'A3',
      a4: 'A4',
      a5: 'A5',
      letter: 'Letter',
      legal: 'Legal',
      f4: 'F4 (HVS)',
    },
    orientationLabel: 'Orientasi',
    portrait: 'Potret',
    landscape: 'Lanskap',
    autoOrientation: 'Ikuti Gambar',
    autoOrientationHint: 'Tiap halaman otomatis ngikutin orientasi gambarnya masing-masing — gambar lebar jadi halaman lanskap, gambar tinggi jadi halaman potret.',
    marginLabel: 'Margin',
    withMargin: 'Dengan Margin',
    noMargin: 'Tanpa Margin',
    marginHint: 'Tanpa margin: gambar penuh sampai tepi halaman (full-bleed). Dengan margin: ada jarak putih di semua sisi.',
    compressionLabel: 'Kompresi',
    compressionOptions: {
      high: 'Kualitas Tinggi',
      balanced: 'Seimbang',
      small: 'Ukuran Kecil',
    },
    compressionHint:
      'Bukan kualitas JPEG yang diturunin — resolusi gambar yang disesuaikan biar pas sama ukuran halaman & DPI cetak, jadi gak ada pixel nganggur yang cuma nambahin ukuran file. "Seimbang" udah tajam banget buat dibaca atau di-print biasa; "Ukuran Kecil" baru kelihatan sedikit lembek kalau di-zoom jauh.',
    convert: 'Buat PDF',
    converting: 'Memproses...',
    resultTitle: 'PDF siap diunduh',
    pageCount: (n: number) => (n === 1 ? '1 halaman' : `${n} halaman`),
    download: 'Unduh',
    downloadSuccessTitle: 'Unduh berhasil',
    downloadSuccess: (name: string) => name,
    clearAll: 'Hapus semua',
  },
  htmlToPdfPage: {
    eyebrow: 'ALAT · HTML KE PDF',
    title: 'HTML ke PDF',
    desc: 'Ubah kode HTML jadi file PDF dengan mudah — tempel kode atau pilih file .html, atur ukuran kertas & margin, lalu unduh hasilnya.',
    sourceLabel: 'Sumber HTML',
    pasteMode: 'Tempel Kode',
    uploadMode: 'Upload File',
    pastePlaceholder: '<!DOCTYPE html>\n<html>\n  <body>\n    <h1>Halo dari VoiTzu Tools!</h1>\n    <p>Tulis atau tempel HTML lo di sini.</p>\n  </body>\n</html>',
    dropTitle: 'Drop file .html di sini atau klik buat pilih',
    dropSub: 'File HTML tunggal (.html / .htm)',
    removeFile: 'Hapus file ini',
    noContentHint: 'Tempel kode HTML atau upload file dulu buat mulai.',
    previewLabel: 'Preview',
    paperSizeLabel: 'Ukuran Kertas',
    paperSizeNames: {
      a3: 'A3',
      a4: 'A4',
      a5: 'A5',
      letter: 'Letter',
      legal: 'Legal',
      f4: 'F4 (HVS)',
    },
    orientationLabel: 'Orientasi',
    portrait: 'Potret',
    landscape: 'Lanskap',
    autoOrientation: 'Ikuti Konten',
    autoOrientationHint: 'Bentuk kontennya dideteksi otomatis sekali di awal — kalau lebih lebar dari tinggi (kayak sertifikat/slide), jadi lanskap; kalau lebih tinggi (kayak artikel/laporan), jadi potret.',
    marginLabel: 'Margin',
    withMargin: 'Dengan Margin',
    noMargin: 'Tanpa Margin',
    marginHint: 'Tanpa margin: konten penuh sampai tepi halaman. Dengan margin: ada jarak putih di semua sisi, kayak dokumen biasa.',
    resolutionLabel: 'Kualitas Render',
    resolutionOptions: {
      standard: 'Standar',
      sharp: 'Tajam',
    },
    resolutionHint: '"Tajam" merender di resolusi lebih tinggi — teks & elemen lebih jernih kalau di-zoom, tapi ukuran file jadi lebih besar dan prosesnya sedikit lebih lama.',
    convert: 'Buat PDF',
    converting: 'Merender...',
    resultTitle: 'PDF siap diunduh',
    pageCount: (n: number) => (n === 1 ? '1 halaman' : `${n} halaman`),
    download: 'Unduh',
    downloadSuccessTitle: 'Unduh berhasil',
    downloadSuccess: (name: string) => name,
    clearAll: 'Hapus semua',
    renderError: 'Gagal merender HTML. Coba periksa lagi kode/file-nya.',
  },
  pdfCompressorPage: {
    eyebrow: 'ALAT · KOMPRES PDF',
    title: 'Kompres PDF',
    desc: 'Perkecil ukuran file PDF dengan cepat — pilih level kompresi yang kamu mau, lalu unduh hasilnya.',
    sourceLabel: 'Sumber PDF',
    dropTitle: 'Drop file PDF di sini atau klik buat pilih',
    dropSub: 'Maks 25MB per file',
    removeFile: 'Hapus file ini',
    levelLabel: 'Level Kompresi',
    levelOptions: {
      low: 'Rendah',
      medium: 'Sedang',
      high: 'Tinggi',
    },
    levelHints: {
      low: 'Kompresi ringan — kualitas gambar dijaga tinggi, ukuran file berkurang sedikit. Cocok buat dokumen yang butuh detail tajam.',
      medium: 'Seimbang antara ukuran dan kualitas — pilihan yang pas buat kebanyakan dokumen.',
      high: 'Kompresi kuat — ukuran file paling kecil, tapi kualitas gambar di dalam PDF ikut turun. Cocok buat kirim cepat lewat chat/email.',
    },
    compress: 'Kompres PDF',
    compressing: 'Mengompres...',
    resultTitle: 'PDF berhasil dikompres',
    pageCount: (n: number) => (n === 1 ? '1 halaman' : `${n} halaman`),
    reduction: (pct: number) => `-${pct}%`,
    download: 'Unduh',
    downloadSuccessTitle: 'Unduh berhasil',
    downloadSuccess: (name: string) => name,
    clearAll: 'Hapus semua',
    errorInvalidType: 'File harus berformat PDF.',
    errorTooLarge: (maxMb: number) => `File kegedean, maks ${maxMb}MB.`,
    compressError: 'Gagal mengompres PDF. Coba file lain atau level kompresi berbeda.',
  },
  docxToHtmlPage: {
    eyebrow: 'ALAT · DOCX KE HTML',
    title: 'DOCX ke HTML',
    desc: 'Ubah dokumen Word (.docx) jadi file HTML — heading, paragraf, list, tabel, dan gambar di dalamnya ikut dikonversi secara otomatis.',
    dropTitle: 'Drop file .docx di sini atau klik buat pilih',
    dropSub: 'File Word (.docx) — bisa banyak file sekaligus',
    removeItem: 'Hapus file ini dari antrean',
    itemsSelected: (n: number) => (n === 1 ? '1 file dipilih' : `${n} file dipilih`),
    includeStyles: 'Sertakan Styling Dasar',
    includeStylesHint: 'Kalau aktif, HTML hasil convert dibungkus tampilan kartu bertema VoiTzu Tools — heading beraksen gradient, tabel & list didesain, bukan cuma teks item-putih polos. Kalau dimatiin, hasilnya cuma markup polos dari isi dokumennya aja — cocok buat ditempel ke sistem lain yang udah punya CSS sendiri.',
    convert: 'Convert Semua File',
    converting: 'Memproses...',
    waiting: 'Menunggu convert',
    conversionWarning: 'Ada bagian yang gak sepenuhnya kekonversi (mis. gaya tertentu) — tetap kebuka normal.',
    download: 'Unduh',
    downloadAll: 'Unduh Semua',
    downloadSuccess: (name: string) => `${name} berhasil diunduh`,
    downloadAllSuccess: (n: number) => (n === 1 ? '1 file diunduh' : `${n} file diunduh`),
    clearAll: 'Hapus semua',
    convertError: 'Gagal convert file ini — pastikan formatnya .docx yang valid.',
  },
  qrGeneratorPage: {
    eyebrow: 'ALAT · PEMBUAT KODE QR',
    title: 'Pembuat Kode QR',
    desc: 'Buat kode QR dari teks, link, WiFi, atau kontak dengan cepat — pilih ukuran yang kamu mau, lalu download hasilnya dalam format PNG.',
    typeLabel: 'Tipe QR',
    typeOptions: { text: 'Teks/Link', wifi: 'WiFi', vcard: 'Kontak' },
    inputLabel: 'Teks atau Link',
    placeholder: 'Contoh: https://tools.voitzu.site',
    ssidLabel: 'Nama WiFi (SSID)',
    ssidPlaceholder: 'Contoh: Rumah-2.4G',
    passwordLabel: 'Password',
    passwordPlaceholder: 'Password WiFi',
    encryptionLabel: 'Jenis Keamanan',
    encryptionOptions: { WPA: 'WPA/WPA2', WEP: 'WEP', nopass: 'Tanpa Password' },
    hiddenLabel: 'Jaringan tersembunyi',
    nameLabel: 'Nama',
    namePlaceholder: 'Nama lengkap',
    phoneLabel: 'Nomor Telepon',
    phonePlaceholder: 'Contoh: 081234567890',
    emailLabel: 'Email (opsional)',
    emailPlaceholder: 'nama@email.com',
    orgLabel: 'Perusahaan/Organisasi (opsional)',
    orgPlaceholder: 'Contoh: VoiTzu Tools',
    sizeLabel: 'Ukuran',
    sizeOptions: { small: 'Kecil', medium: 'Sedang', large: 'Besar' },
    generate: 'Buat QR',
    generating: 'Membuat...',
    errorEmpty: 'Isi teks atau link dulu.',
    errorEmptySsid: 'Isi nama WiFi (SSID) dulu.',
    errorEmptyName: 'Isi nama kontak dulu.',
    generateError: 'Gagal bikin QR, coba lagi.',
    resultTitle: 'QR Code Siap',
    resultHint: 'Klik kanan atau tombol download buat nyimpen gambarnya.',
    download: 'Download PNG',
    downloadSuccessTitle: 'Berhasil didownload',
    downloadSuccess: (name: string) => `${name} udah kesimpen`,
    clearAll: 'Hapus semua',
  },
  bgRemoverPage: {
    eyebrow: 'ALAT · HAPUS LATAR BELAKANG',
    title: 'Hapus Latar Belakang',
    desc: 'Hapus latar belakang gambar secara otomatis — hasilnya PNG transparan yang siap didownload.',
    dropLabel: 'Drop gambar di sini atau klik buat pilih file',
    dropSub: 'JPG · PNG · WEBP — 1 file setiap proses',
    removing: 'Menghapus latar belakang...',
    etaCalculating: 'Menghitung estimasi waktu...',
    etaAlmostDone: 'Hampir selesai...',
    etaSeconds: (s: number) => `Sekitar ${s} detik lagi`,
    etaMinutes: (m: number) => `Sekitar ${m} menit lagi`,
    errorEmpty: 'Pilih gambar dulu.',
    errorTooBig: 'Ukuran file kebesaran, maks 1MB.',
    errorUnsupported: 'Tipe file tidak didukung.',
    removeError: 'Gagal hapus latar belakang, coba lagi.',
    resultTitle: 'Latar Belakang Terhapus',
    resultHint: 'Klik kanan atau tombol download buat nyimpen gambarnya.',
    download: 'Download PNG',
    downloadSuccessTitle: 'Berhasil didownload',
    downloadSuccess: (name: string) => `${name} udah kesimpen`,
    clearAll: 'Hapus semua',
    tryAnother: 'Coba gambar lain',
  },
  pdfMergeSplitPage: {
    eyebrow: 'ALAT · GABUNG & PISAH PDF',
    title: 'Gabung & Pisah PDF',
    desc: 'Gabungkan beberapa PDF jadi satu, atau pisahkan satu PDF jadi beberapa file, dengan cepat dan mudah.',
    tabMerge: 'Gabung',
    tabSplit: 'Pisah',
    dropLabelMerge: 'Drop beberapa file PDF di sini atau klik buat pilih file',
    dropLabelSplit: 'Drop satu file PDF di sini atau klik buat pilih file',
    dropSub: 'PDF',
    addMore: '+ Tambah file lain',
    errorUnsupported: 'Tipe file tidak didukung, cuma PDF.',
    readError: 'Gagal baca file PDF-nya.',
    mergeError: 'Gagal gabungin PDF, coba lagi.',
    splitError: 'Gagal misahin PDF, coba lagi.',
    rangeError: 'Format halamannya salah, contoh: 1-3,5,7-9.',
    mergeButton: 'Gabungkan',
    splitButton: 'Pisahkan',
    clearAll: 'Hapus semua',
    download: 'Download',
    downloadSuccessTitle: 'Berhasil didownload',
    downloadSuccess: (name: string) => `${name} udah kesimpen`,
    readingFile: 'Membaca file...',
    pageCount: (n: number) => `${n} halaman`,
    splitModeAll: 'Setiap halaman jadi file terpisah',
    splitModeRange: 'Rentang halaman kustom',
    rangePlaceholder: 'contoh: 1-3,5,7-9',
    rangeHint: (n: number) => `Total ${n} halaman. Pisahkan dengan koma, pakai tanda strip buat rentang.`,
    autoCompressHint: 'PDF dengan banyak gambar otomatis dikompres dulu (kualitas dijaga tinggi) biar ukurannya lebih kecil.',
    autoCompressed: (from: string, to: string) => `Otomatis dikompres: ${from} → ${to}`,
    largeFileHint: (size: string) => `File ${size} bakal lebih hemat kalau dikompres dulu.`,
    largeFileCta: 'Buka Kompres PDF',
  },
  scanToolPage: {
    eyebrow: 'ALAT · SCAN KE PDF',
    title: 'Scan ke PDF',
    desc: 'Scan dokumen pakai kamera atau pilih gambar dari galeri, lalu jadikan satu PDF yang rapi.',
    toastTitle: 'Pemberitahuan',
    cameraError: 'Gagal membuka kamera. Pastikan izin kamera telah diberikan.',
    cameraPermissionDenied: 'Akses kamera ditolak. Izinkan akses kamera lewat pengaturan situs di browser kamu, lalu coba lagi.',
    cameraNotFound: 'Kamera gak ditemukan di perangkat ini.',
    cameraInUse: 'Kamera lagi dipakai aplikasi lain. Tutup aplikasi itu, lalu coba lagi.',
    cameraUnsupported: 'Browser atau perangkat ini gak mendukung akses kamera.',
    captureSuccess: 'Foto berhasil diambil',
    closeCamera: 'Tutup Kamera',
    switchCamera: 'Balik Kamera',
    capture: 'Ambil Foto',
    openingCamera: 'Membuka Kamera...',
    openCamera: 'Buka Kamera',
    openCameraSub: 'Scan dokumen langsung',
    dropTitle: 'Drop gambar yang mau di-scan di sini atau klik buat pilih file',
    generateError: 'Gagal bikin PDF, coba lagi.',
    pagesSelected: (n: number) => (n === 1 ? '1 halaman dipilih' : `${n} halaman dipilih`),
    tapFilterHint: 'Ketuk gambar untuk ganti filter',
    filterShort: {
      original: 'ASLI',
      grayscale: 'ABU',
      bw: 'B/W',
    },
    removeImage: 'Hapus gambar ini',
    paperSizeLabel: 'Ukuran Kertas',
    paperSizeNames: {
      a3: 'A3',
      a4: 'A4',
      a5: 'A5',
      letter: 'Letter',
      legal: 'Legal',
      f4: 'F4 (HVS)',
    },
    orientationLabel: 'Orientasi',
    portrait: 'Potret',
    landscape: 'Lanskap',
    autoOrientation: 'Otomatis',
    autoOrientationHint: 'Tiap halaman otomatis menyesuaikan bentuk asli gambarnya.',
    marginLabel: 'Margin',
    withMargin: 'Dengan Margin',
    noMargin: 'Tanpa Margin',
    marginHint: 'Tanpa margin: gambar penuh. Dengan margin: ada jarak putih di pinggir halaman.',
    compressionLabel: 'Kompresi',
    compressionOptions: {
      high: 'Kualitas Tinggi',
      balanced: 'Seimbang',
      small: 'Ukuran Kecil',
    },
    compressionHint: 'Resolusi gambar disesuaikan agar pas dengan halaman PDF.',
    converting: 'Memproses...',
    convert: 'Buat PDF',
    resultTitle: 'PDF siap diunduh',
    pageCount: (n: number) => (n === 1 ? '1 halaman' : `${n} halaman`),
    download: 'Unduh',
    downloadSuccess: (name: string) => `${name} berhasil diunduh`,
    clearAll: 'Hapus semua',
  },
  installPrompt: {
    title: 'Instal VoiTzu Tools?',
    subtitle: 'Akses lebih cepat lewat homescreen',
    install: 'Instal',
  },
};

const en: typeof id = {
  nav: {
    toolsLabel: 'Tools',
    imageConverter: 'Image Converter',
    imageConverterDesc: 'Convert & compress',
    imageToPdf: 'Image to PDF',
    imageToPdfDesc: 'Combine images into one PDF',
    htmlToPdf: 'HTML to PDF',
    htmlToPdfDesc: 'Turn HTML code into a PDF',
    docxToHtml: 'DOCX to HTML',
    docxToHtmlDesc: 'Turn a Word document into HTML',
    pdfCompressor: 'PDF Compressor',
    pdfCompressorDesc: 'Shrink PDF file size',
    qrGenerator: 'QR Generator',
    qrGeneratorDesc: 'Generate a QR code',
    bgRemover: 'Background Remover',
    bgRemoverDesc: 'Remove image background',
    pdfMergeSplit: 'Merge & Split PDF',
    pdfMergeSplitDesc: 'Merge or split PDF pages',
    scanToPdf: 'Scan to PDF',
    scanToPdfDesc: 'Scan documents into a PDF',
    soon: 'SOON',
  },
  sidebar: {
    storageStatus: 'Processed 100% locally',
    effectsLabel: 'Background Animation',
    effects: {
      off: 'Off',
      boxes: 'Floating Boxes',
      particles: 'Particles',
      network: 'Network',
      bubbles: 'Bubbles',
      comets: 'Comets',
    },
  },
  theme: {
    dark: 'Dark',
    light: 'Light',
    system: 'System',
    accents: {
      purple: 'Purple',
      green: 'Green',
      yellow: 'Yellow',
      blue: 'Blue',
      orange: 'Orange',
      pink: 'Pink',
      teal: 'Teal',
      red: 'Red',
    },
  },
  toolsPage: {
    title: 'All tools',
    subtitle: 'Pick a tool to use — fast, lightweight, and ready to go.',
  },
  search: {
    openLabel: 'Search',
    placeholder: 'Search tools or pages...',
    toolsGroup: 'Tools',
    pagesGroup: 'Pages',
    noResults: (query: string) => `No results for "${query}"`,
    clearLabel: 'Clear search',
    tapHint: 'Tap to select',
    navHint: 'navigate',
    selectHint: 'select',
    closeHint: 'close',
    soon: 'Soon',
    pages: {
      howItWorks: 'Learn how VoiTzu Tools works, step by step',
      privacy: 'Our privacy policy and what data we store',
      contact: 'Get in touch with the VoiTzu Tools team',
    },
  },
  footer: {
    tagline:
      'A set of small, fast, and free tools — built to get your file conversions done in seconds.',
    toolsTitle: 'Tools',
    infoTitle: 'Info',
    howItWorks: 'How it works',
    privacy: 'Privacy',
    contact: 'Contact',
    soon: 'soon',
    madeWith: 'Built with Next.js & Supabase',
  },
  page: {
    eyebrow: 'TOOLS · IMAGE CONVERTER',
    title: 'Image Converter',
    desc: 'Convert images to WebP, PNG, or JPG instantly and hassle-free. Set quality and target file size independently, then download the result in seconds.',
    dropTitle: 'Drop an image here or click to choose a file',
    dropSub: 'JPG · PNG · WEBP · GIF · BMP — multiple files supported',
    removeItem: 'Remove this image from the queue',
    formatOutput: 'Output Format',
    quality: 'Quality',
    lossless: 'Lossless',
    qualityHintPng: 'PNG is lossless, so there is no quality setting.',
    qualityHint:
      'This quality is applied as-is — it is never lowered automatically. If the file is still too big, the dimensions get shrunk instead, not the quality.',
    targetSize: 'Target File Size',
    targetHint: (max: number) =>
      `Max ${max}KB (1MB). If the result at your chosen quality is still bigger than the target, the image is progressively resized until it fits — quality stays the same.`,
    convert: 'Convert All Files',
    converting: 'Processing...',
    waiting: 'Waiting to convert',
    download: 'Download',
    downloadAll: 'Download All',
    downloadAllSuccess: (n: number) => (n === 1 ? '1 file downloaded' : `${n} files downloaded`),
    downloadSuccessTitle: 'Download successful',
    downloadSuccess: (name: string) => name,
    clearAll: 'Clear all',
    targetNotReached: '· target not reached, this is the smallest possible',
  },
  privacy: {
    eyebrow: 'INFO · PRIVACY',
    title: 'Privacy Policy',
    intro:
      "Short version: your images are processed directly in your browser and never uploaded in their original form. This page explains exactly what data we do touch, and why.",
    updated: "In effect since the first time you opened VoiTzu Tools — there's no hidden alternate version.",
    backLabel: 'Back to Image Converter',
    sections: [
      {
        heading: 'What We Process',
        body: 'Converting, resizing, and compressing images all happen in your browser via the Canvas API — the original file is never sent to any server. The server only receives the final result, after you click convert.',
      },
      {
        heading: 'Data We Store',
        body: "The converted result (not the original file) is automatically backed up to Supabase Storage so you can re-download it later if needed. Filenames are randomized, and we don't store metadata like location, device, or your identity alongside it.",
      },
      {
        heading: 'Preferences in Your Browser',
        body: "Your theme (dark/light), accent color, and language choice are stored in your own browser's localStorage. This never gets sent to our servers — it's purely so the interface stays the way you left it next time you visit.",
      },
      {
        heading: 'Third Parties',
        body: "We use Supabase Storage to back up converted results. There's no Google Analytics, Meta Pixel, or any other ad tracker installed on VoiTzu Tools.",
      },
      {
        heading: 'Security',
        body: "All traffic to the server is encrypted over HTTPS. Since we never handle your original files or personal data, the risk surface stays as small as possible.",
      },
      {
        heading: 'Your Rights',
        body: 'You can request deletion of any converted result stored on our server at any time — just reach out via the contact below with the filename or roughly when you uploaded it.',
      },
      {
        heading: 'Contact',
        body: 'Questions about privacy? Email us at cs.voitzu@gmail.com — we do our best to reply quickly.',
      },
    ],
  },
  contact: {
    eyebrow: 'INFO · CONTACT',
    title: 'Get in Touch',
    intro:
      "Have a question, bug report, or feature idea for VoiTzu Tools? Send a message through the form below or email us directly — we read everything.",
    backLabel: 'Back to Image Converter',
    infoCardsTitle: 'Other Ways to Reach Us',
    email: 'cs.voitzu@gmail.com',
    emailNote: 'Usually replied to within 1–2 business days',
    responseTitle: 'Response Time',
    responseBody: "We're a small team, so thanks for your patience — you'll usually hear back within 1–2 business days.",
    bugTitle: 'Found a Bug?',
    bugBody: 'Mention your browser, the image format, and the steps to reproduce it so we can look into it faster.',
    form: {
      nameLabel: 'Name',
      namePlaceholder: 'Your name',
      emailLabel: 'Email',
      emailPlaceholder: 'you@email.com',
      subjectLabel: 'Topic',
      subjectPlaceholder: 'Choose a topic',
      subjectOptions: ['General question', 'Bug report', 'Feature idea', 'Other'],
      messageLabel: 'Message',
      messagePlaceholder: 'Write your message here...',
      submit: 'Send via Email',
      note: "This button opens your default email app with the message pre-filled — we don't have a server-side form yet.",
    },
  },
  howItWorks: {
    eyebrow: 'INFO · HOW IT WORKS',
    title: 'How VoiTzu Tools Works',
    intro:
      'Every image conversion happens right in your browser, not on our servers. Here\'s the flow from upload to a downloadable file.',
    backLabel: 'Back to Image Converter',
    steps: [
      {
        heading: 'Drop or Select an Image',
        body: 'Drag files into the drop area or click to pick from your device. Multiple files at once are supported — JPG, PNG, WebP, GIF, and BMP are all accepted as input.',
      },
      {
        heading: 'Set Format, Quality & Size',
        body: 'Choose the output format (WebP/JPG/PNG), drag the quality slider, and set a target file size if you need one. These two settings are independent — quality is never auto-lowered to hit the size target.',
      },
      {
        heading: 'Processed in Your Browser',
        body: "Once you click convert, VoiTzu Tools uses the browser's built-in Canvas API to re-encode the image. The original file never leaves your device at this stage.",
      },
      {
        heading: 'Result Auto-backed Up',
        body: 'After processing, only the final result (not the original file) is sent and stored in Supabase Storage, so you can still access it after a page reload or from another device.',
      },
      {
        heading: 'Download Anytime',
        body: "Click download to save the result to your device. That's it — no watermark, no hidden limits.",
      },
    ],
    note: 'Curious what data we actually store? Read the full details on the Privacy page.',
    noteLink: 'View Privacy Policy',
  },
  pdfToolPage: {
    eyebrow: 'TOOLS · IMAGE TO PDF',
    title: 'Image to PDF',
    desc: 'Combine one or many images into a single PDF in seconds. Set the page margin and orientation, or let each page match its image automatically.',
    dropTitle: 'Drop images here or click to choose files',
    dropSub: 'JPG · PNG · WEBP · GIF · BMP — pick multiple, selection order becomes page order',
    imagesSelected: (n: number) => (n === 1 ? '1 image selected' : `${n} images selected`),
    removeImage: 'Remove this image',
    paperSizeLabel: 'Paper Size',
    paperSizeNames: {
      a3: 'A3',
      a4: 'A4',
      a5: 'A5',
      letter: 'Letter',
      legal: 'Legal',
      f4: 'Folio (F4)',
    },
    orientationLabel: 'Orientation',
    portrait: 'Portrait',
    landscape: 'Landscape',
    autoOrientation: 'Match Image',
    autoOrientationHint: 'Each page automatically matches its own image\'s orientation — wide photos get a landscape page, tall ones get portrait.',
    marginLabel: 'Margin',
    withMargin: 'With Margin',
    noMargin: 'No Margin',
    marginHint: 'No margin: the image fills the page edge-to-edge (full-bleed). With margin: white space is added on every side.',
    compressionLabel: 'Compression',
    compressionOptions: {
      high: 'High Quality',
      balanced: 'Balanced',
      small: 'Small Size',
    },
    compressionHint:
      "JPEG quality isn't lowered — the image resolution is matched to the page size and print DPI instead, so there are no wasted pixels inflating the file. \"Balanced\" is still sharp for reading or normal printing; \"Small Size\" only starts looking a bit soft if you zoom in a lot.",
    convert: 'Create PDF',
    converting: 'Processing...',
    resultTitle: 'PDF ready to download',
    pageCount: (n: number) => (n === 1 ? '1 page' : `${n} pages`),
    download: 'Download',
    downloadSuccessTitle: 'Download successful',
    downloadSuccess: (name: string) => name,
    clearAll: 'Clear all',
  },
  htmlToPdfPage: {
    eyebrow: 'TOOL · HTML TO PDF',
    title: 'HTML to PDF',
    desc: 'Turn HTML code into a PDF with ease — paste code or select an .html file, set paper size & margins, then download the result.',
    sourceLabel: 'HTML Source',
    pasteMode: 'Paste Code',
    uploadMode: 'Upload File',
    pastePlaceholder: '<!DOCTYPE html>\n<html>\n  <body>\n    <h1>Hello from VoiTzu Tools!</h1>\n    <p>Write or paste your HTML here.</p>\n  </body>\n</html>',
    dropTitle: 'Drop an .html file here or click to select',
    dropSub: 'A single HTML file (.html / .htm)',
    removeFile: 'Remove this file',
    noContentHint: 'Paste some HTML or upload a file to get started.',
    previewLabel: 'Preview',
    paperSizeLabel: 'Paper Size',
    paperSizeNames: {
      a3: 'A3',
      a4: 'A4',
      a5: 'A5',
      letter: 'Letter',
      legal: 'Legal',
      f4: 'F4 (HVS)',
    },
    orientationLabel: 'Orientation',
    portrait: 'Portrait',
    landscape: 'Landscape',
    autoOrientation: 'Match Content',
    autoOrientationHint: "The content's shape is auto-detected once up front — wider than it is tall (like a certificate/slide) becomes landscape; taller (like an article/report) becomes portrait.",
    marginLabel: 'Margin',
    withMargin: 'With Margin',
    noMargin: 'No Margin',
    marginHint: 'No margin: content fills the page edge-to-edge. With margin: white space is added on every side, like a normal document.',
    resolutionLabel: 'Render Quality',
    resolutionOptions: {
      standard: 'Standard',
      sharp: 'Sharp',
    },
    resolutionHint: '"Sharp" renders at a higher resolution — crisper text and elements when zoomed in, but a larger file size and slightly longer processing time.',
    convert: 'Create PDF',
    converting: 'Rendering...',
    resultTitle: 'PDF ready to download',
    pageCount: (n: number) => (n === 1 ? '1 page' : `${n} pages`),
    download: 'Download',
    downloadSuccessTitle: 'Download successful',
    downloadSuccess: (name: string) => name,
    clearAll: 'Clear all',
    renderError: 'Failed to render the HTML. Double-check your code/file.',
  },
  pdfCompressorPage: {
    eyebrow: 'TOOL · PDF COMPRESSOR',
    title: 'Compress PDF',
    desc: 'Shrink your PDF file size in seconds — pick a compression level, then download the result.',
    sourceLabel: 'PDF Source',
    dropTitle: 'Drop a PDF file here or click to select',
    dropSub: 'Max 25MB per file',
    removeFile: 'Remove this file',
    levelLabel: 'Compression Level',
    levelOptions: {
      low: 'Low',
      medium: 'Medium',
      high: 'High',
    },
    levelHints: {
      low: 'Light compression — image quality stays high, file size drops a little. Good for documents that need sharp detail.',
      medium: 'A balance between size and quality — the right pick for most documents.',
      high: 'Strong compression — smallest file size, but image quality inside the PDF drops noticeably. Good for quick sharing over chat/email.',
    },
    compress: 'Compress PDF',
    compressing: 'Compressing...',
    resultTitle: 'PDF compressed successfully',
    pageCount: (n: number) => (n === 1 ? '1 page' : `${n} pages`),
    reduction: (pct: number) => `-${pct}%`,
    download: 'Download',
    downloadSuccessTitle: 'Download successful',
    downloadSuccess: (name: string) => name,
    clearAll: 'Clear all',
    errorInvalidType: 'File must be a PDF.',
    errorTooLarge: (maxMb: number) => `File too large, max ${maxMb}MB.`,
    compressError: 'Failed to compress the PDF. Try a different file or compression level.',
  },
  docxToHtmlPage: {
    eyebrow: 'TOOL · DOCX TO HTML',
    title: 'DOCX to HTML',
    desc: 'Turn a Word document (.docx) into an HTML file — headings, paragraphs, lists, tables, and embedded images are all converted automatically.',
    dropTitle: 'Drop .docx files here or click to choose',
    dropSub: 'Word documents (.docx) — multiple files supported',
    removeItem: 'Remove this file from the queue',
    itemsSelected: (n: number) => (n === 1 ? '1 file selected' : `${n} files selected`),
    includeStyles: 'Include Basic Styling',
    includeStylesHint: "When on, the converted HTML is wrapped in a VoiTzu Tools-themed card layout — gradient-accented headings, styled tables and lists, not just plain black-on-white text. When off, you get plain markup for just the document's content — handy for pasting into another system that already has its own CSS.",
    convert: 'Convert All Files',
    converting: 'Processing...',
    waiting: 'Waiting to convert',
    conversionWarning: "Some parts didn't fully convert (e.g. certain styles) — it'll still open fine.",
    download: 'Download',
    downloadAll: 'Download All',
    downloadSuccess: (name: string) => `${name} downloaded`,
    downloadAllSuccess: (n: number) => (n === 1 ? '1 file downloaded' : `${n} files downloaded`),
    clearAll: 'Clear all',
    convertError: "Couldn't convert this file — make sure it's a valid .docx.",
  },
  qrGeneratorPage: {
    eyebrow: 'TOOL · QR GENERATOR',
    title: 'QR Generator',
    desc: 'Turn text, a link, WiFi details, or a contact into a QR code in seconds — pick a size, then download the PNG.',
    typeLabel: 'QR Type',
    typeOptions: { text: 'Text/Link', wifi: 'WiFi', vcard: 'Contact' },
    inputLabel: 'Text or Link',
    placeholder: 'e.g. https://tools.voitzu.site',
    ssidLabel: 'Network Name (SSID)',
    ssidPlaceholder: 'e.g. Home-2.4G',
    passwordLabel: 'Password',
    passwordPlaceholder: 'WiFi password',
    encryptionLabel: 'Security Type',
    encryptionOptions: { WPA: 'WPA/WPA2', WEP: 'WEP', nopass: 'No Password' },
    hiddenLabel: 'Hidden network',
    nameLabel: 'Name',
    namePlaceholder: 'Full name',
    phoneLabel: 'Phone Number',
    phonePlaceholder: 'e.g. +1 555 123 4567',
    emailLabel: 'Email (optional)',
    emailPlaceholder: 'name@email.com',
    orgLabel: 'Company/Organization (optional)',
    orgPlaceholder: 'e.g. VoiTzu Tools',
    sizeLabel: 'Size',
    sizeOptions: { small: 'Small', medium: 'Medium', large: 'Large' },
    generate: 'Generate QR',
    generating: 'Generating...',
    errorEmpty: 'Enter some text or a link first.',
    errorEmptySsid: 'Enter the WiFi network name (SSID) first.',
    errorEmptyName: 'Enter a contact name first.',
    generateError: 'Failed to generate the QR code, try again.',
    resultTitle: 'QR Code Ready',
    resultHint: 'Right-click or use the download button to save the image.',
    download: 'Download PNG',
    downloadSuccessTitle: 'Download successful',
    downloadSuccess: (name: string) => `${name} saved`,
    clearAll: 'Clear all',
  },
  bgRemoverPage: {
    eyebrow: 'TOOL · BACKGROUND REMOVER',
    title: 'Background Remover',
    desc: 'Automatically remove an image background — the result is a transparent PNG ready to download.',
    dropLabel: 'Drop an image here or click to choose a file',
    dropSub: 'JPG · PNG · WEBP — 1 file per run',
    removing: 'Removing background...',
    etaCalculating: 'Estimating time...',
    etaAlmostDone: 'Almost done...',
    etaSeconds: (s: number) => `About ${s}s left`,
    etaMinutes: (m: number) => `About ${m}m left`,
    errorEmpty: 'Choose an image first.',
    errorTooBig: 'File is too large, max 1MB.',
    errorUnsupported: 'File type not supported.',
    removeError: 'Failed to remove the background, try again.',
    resultTitle: 'Background Removed',
    resultHint: 'Right-click or use the download button to save the image.',
    download: 'Download PNG',
    downloadSuccessTitle: 'Download successful',
    downloadSuccess: (name: string) => `${name} saved`,
    clearAll: 'Clear all',
    tryAnother: 'Try another image',
  },
  pdfMergeSplitPage: {
    eyebrow: 'TOOL · MERGE & SPLIT PDF',
    title: 'Merge & Split PDF',
    desc: 'Combine several PDFs into one, or split a single PDF into multiple files, quickly and easily.',
    tabMerge: 'Merge',
    tabSplit: 'Split',
    dropLabelMerge: 'Drop multiple PDF files here or click to choose files',
    dropLabelSplit: 'Drop a PDF file here or click to choose a file',
    dropSub: 'PDF',
    addMore: '+ Add more files',
    errorUnsupported: 'File type not supported, PDF only.',
    readError: 'Failed to read the PDF file.',
    mergeError: 'Failed to merge the PDFs, try again.',
    splitError: 'Failed to split the PDF, try again.',
    rangeError: 'Invalid page range, e.g. 1-3,5,7-9.',
    mergeButton: 'Merge',
    splitButton: 'Split',
    clearAll: 'Clear all',
    download: 'Download',
    downloadSuccessTitle: 'Download successful',
    downloadSuccess: (name: string) => `${name} saved`,
    readingFile: 'Reading file...',
    pageCount: (n: number) => `${n} pages`,
    splitModeAll: 'Every page as a separate file',
    splitModeRange: 'Custom page range',
    rangePlaceholder: 'e.g. 1-3,5,7-9',
    rangeHint: (n: number) => `${n} pages total. Separate with commas, use a dash for ranges.`,
    autoCompressHint: 'PDFs with lots of images are auto-compressed first (quality kept high) to shrink the file size.',
    autoCompressed: (from: string, to: string) => `Auto-compressed: ${from} → ${to}`,
    largeFileHint: (size: string) => `Files around ${size} shrink better with a dedicated compressor.`,
    largeFileCta: 'Open PDF Compressor',
  },
  scanToolPage: {
    eyebrow: 'TOOL · SCAN TO PDF',
    title: 'Scan to PDF',
    desc: 'Scan documents with your camera or select images from your gallery to create a clean PDF.',
    toastTitle: 'Notification',
    cameraError: 'Failed to open camera. Please make sure permissions are granted.',
    cameraPermissionDenied: 'Camera access denied. Allow camera access in your browser\'s site settings, then try again.',
    cameraNotFound: 'No camera found on this device.',
    cameraInUse: 'Camera is currently in use by another app. Close that app, then try again.',
    cameraUnsupported: 'This browser or device does not support camera access.',
    captureSuccess: 'Photo captured successfully',
    closeCamera: 'Close Camera',
    switchCamera: 'Switch Camera',
    capture: 'Capture Photo',
    openingCamera: 'Opening Camera...',
    openCamera: 'Open Camera',
    openCameraSub: 'Scan documents directly',
    dropTitle: 'Drop the images you want to scan here or click to choose files',
    generateError: 'Failed to create the PDF, try again.',
    pagesSelected: (n: number) => (n === 1 ? '1 page selected' : `${n} pages selected`),
    tapFilterHint: 'Tap image to change filter',
    filterShort: {
      original: 'ORIG',
      grayscale: 'GRAY',
      bw: 'B/W',
    },
    removeImage: 'Remove this image',
    paperSizeLabel: 'Paper Size',
    paperSizeNames: {
      a3: 'A3',
      a4: 'A4',
      a5: 'A5',
      letter: 'Letter',
      legal: 'Legal',
      f4: 'Folio (F4)',
    },
    orientationLabel: 'Orientation',
    portrait: 'Portrait',
    landscape: 'Landscape',
    autoOrientation: 'Auto',
    autoOrientationHint: 'Each page automatically matches its own image\'s orientation.',
    marginLabel: 'Margin',
    withMargin: 'With Margin',
    noMargin: 'No Margin',
    marginHint: 'No margin: image fills the page. With margin: white space is added on edges.',
    compressionLabel: 'Compression',
    compressionOptions: {
      high: 'High Quality',
      balanced: 'Balanced',
      small: 'Small Size',
    },
    compressionHint: 'Image resolution is adjusted to fit the PDF page.',
    converting: 'Processing...',
    convert: 'Create PDF',
    resultTitle: 'PDF ready to download',
    pageCount: (n: number) => (n === 1 ? '1 page' : `${n} pages`),
    download: 'Download',
    downloadSuccess: (name: string) => `${name} downloaded successfully`,
    clearAll: 'Clear all',
  },
  installPrompt: {
    title: 'Install VoiTzu Tools?',
    subtitle: 'Faster access from your homescreen',
    install: 'Install',
  },
};

const dictionaries = { id, en };
export type Dict = typeof id;

interface LanguageContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: Dict;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

const LANG_STORAGE_KEY = 'VoiTzu Tools-language';
const LANG_COOKIE_KEY = 'voitzu-lang'; // nama cookie gak boleh pakai spasi

export function LanguageProvider({
  children,
  initialLang = 'id',
}: {
  children: ReactNode;
  initialLang?: Lang;
}) {
  // initialLang datang dari cookie yang dibaca di server (layout.tsx),
  // jadi render pertama sudah langsung pakai bahasa yang benar — tidak
  // perlu nunggu localStorage kebaca di client (itu yang bikin flash id).
  const [lang, setLangState] = useState<Lang>(initialLang);

  function setLang(l: Lang) {
    setLangState(l);
    try {
      window.localStorage.setItem(LANG_STORAGE_KEY, l);
    } catch {}
    // Cookie dibaca server di request berikutnya, expire 1 tahun
    document.cookie = `${LANG_COOKIE_KEY}=${l}; path=/; max-age=31536000; SameSite=Lax; Secure`;
  }

  const value: LanguageContextValue = { lang, setLang, t: dictionaries[lang] };
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within a LanguageProvider');
  return ctx;
}